script: "bundle exec rake spec cucumber"

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile

matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: rbx-18mode
    - rvm: jruby
  include:
    - rvm: 2.0.0
      gemfile: gemfiles/3.2.gemfile
    - rvm: rbx-18mode
      gemfile: gemfiles/3.2.gemfile
    - rvm: jruby
      gemfile: gemfiles/3.2.gemfile
